import type { AgentDef, SpritePalette } from "./types";

const P = (hair: string, skin: string, top: string, bottom: string, shoe: string, accent: string): SpritePalette => ({
  hair,
  skin,
  top,
  bottom,
  shoe,
  accent,
});

const SKIN = ["#F2C6A0", "#D9A177", "#B57C55", "#8C5A3C", "#F7D9BC", "#6E4630"];
const HAIR = ["#2B2118", "#5A3A22", "#C9903F", "#8E3B2F", "#1A1A24", "#6B5B8A", "#D9D2C4"];

export const ROSTER: AgentDef[] = [
  // ─────────────────────────────  MARKETING  ─────────────────────────────
  {
    id: "mkt-01",
    name: "Nora Vela",
    role: "Directora de Contenido",
    dept: "marketing",
    bio: "Planifica el calendario editorial de todos los canales y escribe los borradores largos. Cada mañana lee lo que se publicó ayer, mide qué funcionó y reescribe la línea del mes.",
    model: "opus-5",
    tools: ["Notion", "WordPress", "Ahrefs", "Slack"],
    tasks: [
      "Redactando artículo pilar «Automatizar el cierre contable»",
      "Reescribiendo 4 titulares con bajo CTR",
      "Preparando el calendario editorial de la semana 32",
      "Resumiendo 11 entrevistas de cliente en 3 ángulos",
      "Actualizando 6 posts con datos de julio",
    ],
    palette: P(HAIR[2], SKIN[0], "#FF5FA2", "#2C3466", "#1A1E36", "#FFD1E6"),
    deployedDays: 214,
    baseRuns: 28640,
    baseHours: 6.4,
    cadence: 13,
    successRate: 98.9,
    avgRuntime: 41,
    valuePerRun: 62,
    savedPerRun: 0.28,
    skills: [
      { label: "Redacción", value: 96 },
      { label: "Investigación", value: 88 },
      { label: "SEO", value: 74 },
    ],
  },
  {
    id: "mkt-02",
    name: "Iker Bravo",
    role: "Especialista SEO Técnico",
    dept: "marketing",
    bio: "Rastrea el sitio cada hora buscando enlaces rotos, canonicals duplicados y páginas que pierden posiciones. Abre la corrección ya escrita, no solo el aviso.",
    model: "sonnet-5",
    tools: ["Search Console", "Screaming Frog", "GitHub", "BigQuery"],
    tasks: [
      "Rastreando 12.400 URLs en busca de 404 internos",
      "Corrigiendo 23 canonicals duplicados en /blog",
      "Analizando caída de posiciones en 8 keywords",
      "Generando schema de producto para 340 fichas",
      "Comprimiendo 1.2 GB de imágenes sin pérdida visible",
    ],
    palette: P(HAIR[0], SKIN[1], "#3E7BFF", "#232842", "#14172C", "#9CC0FF"),
    deployedDays: 198,
    baseRuns: 41280,
    baseHours: 7.1,
    cadence: 9,
    successRate: 99.4,
    avgRuntime: 26,
    valuePerRun: 48,
    savedPerRun: 0.19,
    skills: [
      { label: "Auditoría", value: 94 },
      { label: "Datos", value: 91 },
      { label: "Código", value: 79 },
    ],
  },
  {
    id: "mkt-03",
    name: "Lía Ferrer",
    role: "Diseñadora de Creatividades",
    dept: "marketing",
    bio: "Produce las variantes visuales de cada campaña y las adapta a los nueve formatos que piden las plataformas. Descarta sola las que bajan del umbral de atención.",
    model: "opus-5",
    tools: ["Figma", "Meta Ads", "Cloudinary", "Brandfolder"],
    tasks: [
      "Generando 18 variantes del banner de rebajas",
      "Adaptando la campaña «Vuelta» a 9 formatos",
      "Revisando contraste y accesibilidad en 30 piezas",
      "Probando 3 paletas nuevas contra el test A/B",
      "Exportando el kit de marca para el equipo de ventas",
    ],
    palette: P(HAIR[5], SKIN[4], "#B15BFF", "#3A2C5E", "#1D1630", "#E8C4FF"),
    deployedDays: 156,
    baseRuns: 19420,
    baseHours: 5.8,
    cadence: 15,
    successRate: 97.6,
    avgRuntime: 58,
    valuePerRun: 71,
    savedPerRun: 0.34,
    skills: [
      { label: "Composición", value: 93 },
      { label: "Iteración", value: 89 },
      { label: "Marca", value: 85 },
    ],
  },
  {
    id: "mkt-04",
    name: "Bruno Salas",
    role: "Gestor de Medios de Pago",
    dept: "marketing",
    bio: "Reparte 4.200 € de presupuesto diario entre campañas y mueve el dinero cada 20 minutos según el coste por adquisición. Apaga lo que no rinde sin esperar aprobación.",
    model: "opus-5",
    tools: ["Meta Ads", "Google Ads", "TikTok Ads", "Looker"],
    tasks: [
      "Reasignando 480 € de Search a Performance Max",
      "Pausando 6 conjuntos con CPA por encima de 34 €",
      "Subiendo puja un 12 % en la campaña de retargeting",
      "Comparando ROAS por creatividad de los últimos 7 días",
      "Detectando fatiga de anuncio en 3 públicos",
    ],
    palette: P(HAIR[1], SKIN[2], "#FF8A3D", "#2A2F4A", "#171A2E", "#FFD4A8"),
    deployedDays: 231,
    baseRuns: 52180,
    baseHours: 7.6,
    cadence: 7,
    successRate: 99.1,
    avgRuntime: 19,
    valuePerRun: 96,
    savedPerRun: 0.16,
    skills: [
      { label: "Puja", value: 97 },
      { label: "Análisis", value: 92 },
      { label: "Riesgo", value: 81 },
    ],
  },
  {
    id: "mkt-05",
    name: "Mara Ortiz",
    role: "Responsable de Comunidad",
    dept: "marketing",
    bio: "Responde en redes en menos de cuatro minutos y clasifica cada mención por sentimiento. Escala a un humano solo cuando detecta crisis o prensa.",
    model: "sonnet-5",
    tools: ["X", "Instagram", "LinkedIn", "Zendesk"],
    tasks: [
      "Respondiendo 34 menciones pendientes",
      "Clasificando el sentimiento de 210 comentarios",
      "Preparando el hilo de lanzamiento de septiembre",
      "Escalando 2 quejas repetidas a Soporte",
      "Midiendo alcance orgánico frente a la semana pasada",
    ],
    palette: P(HAIR[3], SKIN[0], "#FF4F6E", "#2E2440", "#1A1428", "#FFC2CC"),
    deployedDays: 173,
    baseRuns: 63940,
    baseHours: 7.9,
    cadence: 6,
    successRate: 98.2,
    avgRuntime: 12,
    valuePerRun: 22,
    savedPerRun: 0.11,
    skills: [
      { label: "Tono", value: 91 },
      { label: "Rapidez", value: 96 },
      { label: "Criterio", value: 84 },
    ],
  },
  {
    id: "mkt-06",
    name: "Teo Rincón",
    role: "Arquitecto de Email",
    dept: "marketing",
    bio: "Mantiene vivos 14 flujos de ciclo de vida y personaliza cada envío por comportamiento real, no por segmento fijo. Limpia la lista antes de que la reputación caiga.",
    model: "sonnet-5",
    tools: ["Klaviyo", "Segment", "Postmark", "Snowflake"],
    tasks: [
      "Enviando la secuencia de carrito abandonado a 1.840 perfiles",
      "Probando 2 asuntos en el flujo de bienvenida",
      "Depurando 620 direcciones inactivas",
      "Reescribiendo el correo de renovación anual",
      "Vigilando la tasa de rebote del dominio",
    ],
    palette: P(HAIR[4], SKIN[3], "#38C8C8", "#243A44", "#12222A", "#A6F0F0"),
    deployedDays: 189,
    baseRuns: 47610,
    baseHours: 6.8,
    cadence: 8,
    successRate: 99.6,
    avgRuntime: 23,
    valuePerRun: 58,
    savedPerRun: 0.21,
    skills: [
      { label: "Automatización", value: 95 },
      { label: "Segmentación", value: 90 },
      { label: "Copy", value: 78 },
    ],
  },
  {
    id: "mkt-07",
    name: "Coral Ibáñez",
    role: "Analista de Marca",
    dept: "marketing",
    bio: "Cruza encuestas, reseñas y señales de búsqueda para saber qué piensa el mercado esta semana. Traduce todo a tres decisiones concretas, no a un informe de cuarenta páginas.",
    model: "opus-5",
    tools: ["Typeform", "Trustpilot", "BigQuery", "Miro"],
    tasks: [
      "Sintetizando 480 reseñas de los últimos 30 días",
      "Midiendo notoriedad frente a 4 competidores",
      "Detectando 2 objeciones nuevas en el discurso de compra",
      "Actualizando el mapa de posicionamiento",
      "Preparando el informe semanal para dirección",
    ],
    palette: P(HAIR[6], SKIN[1], "#F2E14C", "#33314A", "#1C1B2C", "#FFF6B0"),
    deployedDays: 142,
    baseRuns: 15380,
    baseHours: 5.2,
    cadence: 18,
    successRate: 97.9,
    avgRuntime: 74,
    valuePerRun: 84,
    savedPerRun: 0.42,
    skills: [
      { label: "Síntesis", value: 94 },
      { label: "Estadística", value: 87 },
      { label: "Narrativa", value: 83 },
    ],
  },

  {
    id: "mkt-08",
    name: "Rita Quiroga",
    role: "Cazadora de Clientes",
    dept: "marketing",
    bio: "Barre el mapa de una ciudad buscando los negocios que encajan con lo que vendes, cruza Instagram y LinkedIn, amplía el radio si hace falta, y les saca el correo del responsable. Entrega la lista lista para llamar, no un informe.",
    model: "opus-5",
    tools: ["Google Maps", "OpenStreetMap", "Instagram", "LinkedIn", "Hunter.io", "HubSpot"],
    tasks: [
      "Barriendo el mapa en busca de negocios que encajan",
      "Cruzando Instagram y LinkedIn de cada negocio",
      "Ampliando el radio para completar la lista",
      "Verificando el correo del responsable con Hunter.io",
      "Preparando la lista para la ronda de llamadas",
    ],
    palette: P(HAIR[6], SKIN[2], "#F5F7FF", "#FF2E93", "#1A1E36", "#FF2E93"),
    deployedDays: 2,
    baseRuns: 148,
    baseHours: 4.2,
    cadence: 11,
    successRate: 97.2,
    avgRuntime: 34,
    valuePerRun: 130,
    savedPerRun: 0.55,
    skills: [
      { label: "Prospección", value: 92 },
      { label: "Verificación", value: 88 },
      { label: "Cartografía", value: 95 },
    ],
  },

  // ──────────────────────────────  VENTAS  ──────────────────────────────
  {
    id: "sls-01",
    name: "Diego Nieves",
    role: "Prospector Outbound",
    dept: "ventas",
    bio: "Construye listas de empresas que encajan y escribe el primer mensaje uno a uno. Nunca envía plantilla: cita algo real de la empresa a la que escribe.",
    model: "sonnet-5",
    tools: ["Apollo", "LinkedIn", "HubSpot", "Lemlist"],
    tasks: [
      "Investigando 60 cuentas del sector retail",
      "Escribiendo 24 primeros mensajes personalizados",
      "Verificando correos de 3 nuevas listas",
      "Registrando 18 respuestas en el CRM",
      "Ajustando el mensaje que mejor responde esta semana",
    ],
    palette: P(HAIR[0], SKIN[0], "#3FE38A", "#26304C", "#141B2E", "#B6FFD8"),
    deployedDays: 205,
    baseRuns: 58720,
    baseHours: 7.8,
    cadence: 6,
    successRate: 96.8,
    avgRuntime: 17,
    valuePerRun: 54,
    savedPerRun: 0.18,
    skills: [
      { label: "Prospección", value: 95 },
      { label: "Personalización", value: 89 },
      { label: "Volumen", value: 97 },
    ],
  },
  {
    id: "sls-02",
    name: "Aitana Sol",
    role: "Ejecutiva de Cuentas",
    dept: "ventas",
    bio: "Lleva las 42 oportunidades abiertas por encima de 8.000 €. Prepara cada llamada con el histórico completo del cliente y deja la propuesta lista antes de colgar.",
    model: "opus-5",
    tools: ["HubSpot", "Gong", "DocuSign", "Slack"],
    tasks: [
      "Preparando la llamada con Grupo Ardanza",
      "Actualizando 11 oportunidades tras las reuniones de ayer",
      "Redactando la propuesta de renovación de Vinca",
      "Detectando 3 negocios sin actividad en 14 días",
      "Resumiendo objeciones de la última demo",
    ],
    palette: P(HAIR[2], SKIN[4], "#2FD4A8", "#2A3358", "#161C33", "#9EF5DC"),
    deployedDays: 227,
    baseRuns: 21460,
    baseHours: 8.1,
    cadence: 16,
    successRate: 98.4,
    avgRuntime: 62,
    valuePerRun: 214,
    savedPerRun: 0.38,
    skills: [
      { label: "Cierre", value: 93 },
      { label: "Contexto", value: 96 },
      { label: "Escucha", value: 88 },
    ],
  },
  {
    id: "sls-03",
    name: "Rubén Lara",
    role: "Cualificador de Leads",
    dept: "ventas",
    bio: "Puntúa cada lead que entra en menos de 30 segundos y lo enruta al comercial correcto. Descarta sin miedo lo que no encaja para no llenar el pipeline de humo.",
    model: "haiku-4.5",
    tools: ["HubSpot", "Clearbit", "Calendly", "Twilio"],
    tasks: [
      "Puntuando 47 leads entrados esta mañana",
      "Enrutando 12 oportunidades a la ejecutiva de cuentas",
      "Descartando 9 registros sin encaje de tamaño",
      "Agendando 6 demos automáticamente",
      "Enriqueciendo datos de 31 empresas",
    ],
    palette: P(HAIR[1], SKIN[2], "#5BE8C0", "#233049", "#12192B", "#C4FFEE"),
    deployedDays: 168,
    baseRuns: 88340,
    baseHours: 8.3,
    cadence: 4,
    successRate: 99.2,
    avgRuntime: 8,
    valuePerRun: 31,
    savedPerRun: 0.09,
    skills: [
      { label: "Velocidad", value: 99 },
      { label: "Precisión", value: 90 },
      { label: "Criba", value: 92 },
    ],
  },
  {
    id: "sls-04",
    name: "Vera Campos",
    role: "Especialista en Propuestas",
    dept: "ventas",
    bio: "Convierte notas de reunión en presupuestos firmables con precios, plazos y condiciones ya validadas. Avisa cuando un descuento se sale del margen aprobado.",
    model: "opus-5",
    tools: ["PandaDoc", "HubSpot", "Excel", "Stripe"],
    tasks: [
      "Generando presupuesto de 34.500 € para Marítima Ossa",
      "Comprobando margen en 5 propuestas con descuento",
      "Actualizando la tarifa de septiembre en 3 plantillas",
      "Convirtiendo notas de reunión en pliego técnico",
      "Enviando 4 contratos a firma electrónica",
    ],
    palette: P(HAIR[5], SKIN[0], "#7FE05C", "#2E3552", "#181E33", "#D2FFBC"),
    deployedDays: 191,
    baseRuns: 17920,
    baseHours: 6.9,
    cadence: 17,
    successRate: 99.0,
    avgRuntime: 55,
    valuePerRun: 168,
    savedPerRun: 0.45,
    skills: [
      { label: "Precisión", value: 97 },
      { label: "Margen", value: 91 },
      { label: "Redacción", value: 86 },
    ],
  },
  {
    id: "sls-05",
    name: "Marco Ferraz",
    role: "Operaciones de CRM",
    dept: "ventas",
    bio: "Mantiene el CRM limpio: fusiona duplicados, completa campos vacíos y corrige etapas mal puestas. Sin él, ningún informe de ventas sería fiable.",
    model: "haiku-4.5",
    tools: ["HubSpot", "Zapier", "Snowflake", "Airtable"],
    tasks: [
      "Fusionando 28 contactos duplicados",
      "Rellenando el sector de 140 empresas",
      "Corrigiendo 16 negocios en etapa incorrecta",
      "Sincronizando actividad de correo con el CRM",
      "Regenerando el informe de previsión semanal",
    ],
    palette: P(HAIR[4], SKIN[3], "#49C97A", "#26314A", "#131B2C", "#A9F0C2"),
    deployedDays: 244,
    baseRuns: 96150,
    baseHours: 8.0,
    cadence: 5,
    successRate: 99.7,
    avgRuntime: 9,
    valuePerRun: 26,
    savedPerRun: 0.13,
    skills: [
      { label: "Higiene", value: 98 },
      { label: "Integración", value: 93 },
      { label: "Constancia", value: 99 },
    ],
  },
  {
    id: "sls-06",
    name: "Idoia Rey",
    role: "Éxito de Cliente",
    dept: "ventas",
    bio: "Vigila el uso de las 380 cuentas activas y detecta el abandono antes de que se cancele. Propone la acción concreta que recupera cada cuenta en riesgo.",
    model: "opus-5",
    tools: ["Mixpanel", "Intercom", "HubSpot", "Notion"],
    tasks: [
      "Detectando 7 cuentas con uso a la baja",
      "Preparando el plan de recuperación de Aldabra SL",
      "Enviando el resumen trimestral a 22 clientes",
      "Identificando 5 cuentas listas para ampliar contrato",
      "Cruzando tickets de soporte con riesgo de baja",
    ],
    palette: P(HAIR[6], SKIN[1], "#34D6A4", "#2B3653", "#161F33", "#ADF6E0"),
    deployedDays: 179,
    baseRuns: 24870,
    baseHours: 7.4,
    cadence: 12,
    successRate: 98.1,
    avgRuntime: 44,
    valuePerRun: 142,
    savedPerRun: 0.31,
    skills: [
      { label: "Retención", value: 94 },
      { label: "Señales", value: 92 },
      { label: "Empatía", value: 87 },
    ],
  },
  {
    id: "sls-07",
    name: "Saúl Duarte",
    role: "Analista de Negociación",
    dept: "ventas",
    bio: "Estudia cómo se cerraron los últimos 900 acuerdos y recomienda el siguiente movimiento en cada negociación viva. Sabe cuándo conviene no bajar el precio.",
    model: "opus-5",
    tools: ["Gong", "HubSpot", "BigQuery", "Slack"],
    tasks: [
      "Analizando la contraoferta de Teixidó Group",
      "Calculando probabilidad de cierre de 19 negocios",
      "Recomendando plazo alternativo en 3 negociaciones",
      "Revisando patrones de descuento del trimestre",
      "Alertando de 2 acuerdos con riesgo de estancamiento",
    ],
    palette: P(HAIR[0], SKIN[5], "#26B96F", "#293150", "#141A2E", "#96EEBC"),
    deployedDays: 137,
    baseRuns: 13240,
    baseHours: 6.2,
    cadence: 19,
    successRate: 97.4,
    avgRuntime: 68,
    valuePerRun: 236,
    savedPerRun: 0.4,
    skills: [
      { label: "Estrategia", value: 95 },
      { label: "Predicción", value: 89 },
      { label: "Firmeza", value: 90 },
    ],
  },

  // ───────────────────────────  CONTABILIDAD  ───────────────────────────
  {
    id: "fin-01",
    name: "Elsa Moret",
    role: "Conciliación Bancaria",
    dept: "contabilidad",
    bio: "Cuadra cada movimiento de las seis cuentas del grupo contra facturas y cobros. Lo que no casa lo deja marcado con la explicación, no solo con el aviso.",
    model: "sonnet-5",
    tools: ["Holded", "BBVA API", "Stripe", "Excel"],
    tasks: [
      "Conciliando 214 movimientos del día",
      "Investigando un descuadre de 1.284,60 €",
      "Casando 38 cobros de Stripe con facturas",
      "Marcando 4 apuntes sin justificante",
      "Cerrando la caja de la delegación norte",
    ],
    palette: P(HAIR[2], SKIN[0], "#FFC24B", "#3A3252", "#211C33", "#FFE9B8"),
    deployedDays: 261,
    baseRuns: 71260,
    baseHours: 7.7,
    cadence: 5,
    successRate: 99.8,
    avgRuntime: 11,
    valuePerRun: 34,
    savedPerRun: 0.15,
    skills: [
      { label: "Exactitud", value: 99 },
      { label: "Trazabilidad", value: 96 },
      { label: "Volumen", value: 94 },
    ],
  },
  {
    id: "fin-02",
    name: "Hugo Peña",
    role: "Facturación y Cobros",
    dept: "contabilidad",
    bio: "Emite las facturas del día y persigue los impagos con el tono justo en cada aviso. Escala a jurídico solo cuando pasa de 90 días.",
    model: "haiku-4.5",
    tools: ["Holded", "Stripe", "Gmail", "GoCardless"],
    tasks: [
      "Emitiendo 46 facturas del ciclo de agosto",
      "Enviando 2.º aviso a 13 clientes con retraso",
      "Reintentando 8 cobros con tarjeta caducada",
      "Aplicando 5 abonos aprobados ayer",
      "Actualizando el saldo pendiente por cliente",
    ],
    palette: P(HAIR[1], SKIN[2], "#FFAF3C", "#37304C", "#1F1A2E", "#FFDFA6"),
    deployedDays: 249,
    baseRuns: 82940,
    baseHours: 8.2,
    cadence: 4,
    successRate: 99.5,
    avgRuntime: 7,
    valuePerRun: 41,
    savedPerRun: 0.1,
    skills: [
      { label: "Cobro", value: 96 },
      { label: "Rapidez", value: 98 },
      { label: "Tono", value: 85 },
    ],
  },
  {
    id: "fin-03",
    name: "Nadia Cortés",
    role: "Impuestos y Cumplimiento",
    dept: "contabilidad",
    bio: "Prepara IVA, retenciones e intrastat con el calendario fiscal siempre delante. Revisa cambios normativos cada semana y avisa de lo que afecta a la empresa.",
    model: "opus-5",
    tools: ["AEAT", "Holded", "BOE", "Notion"],
    tasks: [
      "Preparando el modelo 303 del segundo trimestre",
      "Revisando 62 facturas con IVA mal aplicado",
      "Comprobando retenciones de 9 proveedores",
      "Leyendo el cambio normativo publicado el lunes",
      "Cuadrando el intrastat de importaciones",
    ],
    palette: P(HAIR[4], SKIN[3], "#E8A93C", "#332C48", "#1C182B", "#FFD99B"),
    deployedDays: 222,
    baseRuns: 19680,
    baseHours: 6.6,
    cadence: 15,
    successRate: 99.9,
    avgRuntime: 52,
    valuePerRun: 88,
    savedPerRun: 0.36,
    skills: [
      { label: "Normativa", value: 98 },
      { label: "Rigor", value: 99 },
      { label: "Anticipación", value: 90 },
    ],
  },
  {
    id: "fin-04",
    name: "Óscar Villa",
    role: "Nóminas y Personal",
    dept: "contabilidad",
    bio: "Calcula las 74 nóminas del mes con variables, dietas y horas extra ya cruzadas. Detecta el error antes del pago, no en la reclamación.",
    model: "sonnet-5",
    tools: ["A3Nom", "Factorial", "Seg. Social", "Excel"],
    tasks: [
      "Calculando variables de 74 nóminas",
      "Cruzando 318 horas extra con los partes de fichaje",
      "Revisando 3 altas y 1 baja de este mes",
      "Preparando el fichero de remesa bancaria",
      "Comprobando cotizaciones frente al último boletín",
    ],
    palette: P(HAIR[0], SKIN[1], "#D99A2E", "#2F2A45", "#1A1729", "#FFD08A"),
    deployedDays: 236,
    baseRuns: 12470,
    baseHours: 5.9,
    cadence: 20,
    successRate: 99.6,
    avgRuntime: 71,
    valuePerRun: 76,
    savedPerRun: 0.48,
    skills: [
      { label: "Cálculo", value: 97 },
      { label: "Cumplimiento", value: 95 },
      { label: "Discreción", value: 99 },
    ],
  },
  {
    id: "fin-05",
    name: "Ruth Alcaraz",
    role: "Control de Costes",
    dept: "contabilidad",
    bio: "Vigila en qué se va el dinero cada día y compara contra el presupuesto aprobado. Cuando una partida se desvía más de un 8 %, lo dice el mismo día.",
    model: "opus-5",
    tools: ["Looker", "Holded", "Snowflake", "Slack"],
    tasks: [
      "Comparando gasto real contra presupuesto de agosto",
      "Detectando desvío del 11 % en logística inversa",
      "Auditando 27 suscripciones de software activas",
      "Recalculando el margen por línea de producto",
      "Proponiendo 3 recortes sin impacto operativo",
    ],
    palette: P(HAIR[6], SKIN[0], "#F2CE5C", "#38304E", "#201B30", "#FFF0BC"),
    deployedDays: 164,
    baseRuns: 16830,
    baseHours: 6.1,
    cadence: 16,
    successRate: 98.7,
    avgRuntime: 49,
    valuePerRun: 118,
    savedPerRun: 0.33,
    skills: [
      { label: "Análisis", value: 96 },
      { label: "Alerta", value: 93 },
      { label: "Criterio", value: 88 },
    ],
  },

  // ────────────────────────────  LOGÍSTICA  ────────────────────────────
  {
    id: "log-01",
    name: "Kai Moreno",
    role: "Planificador de Rutas",
    dept: "logistica",
    bio: "Reparte los pedidos del día entre los seis domiciliarios y ordena la ruta de cada uno sobre las calles reales de Medellín. Ahorra kilómetros sin romper ninguna ventana de entrega.",
    model: "opus-5",
    tools: ["Routific", "Google Maps", "SAP", "Twilio"],
    tasks: [
      "Repartiendo 40 pedidos entre 6 domiciliarios",
      "Encajando 9 entregas express antes de las 12:00",
      "Ordenando las 9 paradas del furgón por El Poblado",
      "Comparando su plan contra el reparto por orden de llegada",
      "Avisando a 3 clientes de una nueva franja horaria",
    ],
    palette: P(HAIR[0], SKIN[2], "#9B7BFF", "#2C2A50", "#181630", "#D6C9FF"),
    deployedDays: 208,
    baseRuns: 44720,
    baseHours: 8.4,
    cadence: 7,
    successRate: 98.8,
    avgRuntime: 22,
    valuePerRun: 74,
    savedPerRun: 0.24,
    skills: [
      { label: "Optimización", value: 97 },
      { label: "Reacción", value: 94 },
      { label: "Coste", value: 91 },
    ],
  },
  {
    id: "log-02",
    name: "Sira Bonet",
    role: "Control de Inventario",
    dept: "logistica",
    bio: "Cuenta el stock de tres almacenes en tiempo real y lanza el pedido de reposición antes de la rotura. Ajusta el punto de pedido según lo que vendió ayer.",
    model: "sonnet-5",
    tools: ["SAP", "Shopify", "Odoo", "Slack"],
    tasks: [
      "Ajustando el punto de pedido de 240 referencias",
      "Detectando rotura inminente en 6 SKU top",
      "Cuadrando el inventario del almacén de Getafe",
      "Marcando 18 referencias con rotación baja",
      "Lanzando reposición automática de 3 proveedores",
    ],
    palette: P(HAIR[2], SKIN[4], "#8A6BF0", "#2A2848", "#16142B", "#CBBBFF"),
    deployedDays: 217,
    baseRuns: 67350,
    baseHours: 8.1,
    cadence: 5,
    successRate: 99.3,
    avgRuntime: 13,
    valuePerRun: 52,
    savedPerRun: 0.17,
    skills: [
      { label: "Previsión", value: 95 },
      { label: "Exactitud", value: 97 },
      { label: "Reposición", value: 92 },
    ],
  },
  {
    id: "log-03",
    name: "Lorenzo Vidal",
    role: "Gestión de Proveedores",
    dept: "logistica",
    bio: "Negocia plazos y precios con 46 proveedores y puntúa su cumplimiento cada mes. Cambia de proveedor cuando los retrasos pasan de dos veces seguidas.",
    model: "opus-5",
    tools: ["SAP", "Gmail", "Excel", "DocuSign"],
    tasks: [
      "Negociando plazo de entrega con Ferrasa Ibérica",
      "Puntuando el cumplimiento de 46 proveedores",
      "Comparando 4 ofertas para el mismo componente",
      "Reclamando 2 pedidos con 9 días de retraso",
      "Renovando el acuerdo marco de transporte",
    ],
    palette: P(HAIR[1], SKIN[5], "#7B62E0", "#282646", "#141328", "#BFAFFA"),
    deployedDays: 195,
    baseRuns: 14960,
    baseHours: 6.3,
    cadence: 18,
    successRate: 97.8,
    avgRuntime: 64,
    valuePerRun: 158,
    savedPerRun: 0.39,
    skills: [
      { label: "Negociación", value: 93 },
      { label: "Seguimiento", value: 90 },
      { label: "Ahorro", value: 89 },
    ],
  },
  {
    id: "log-04",
    name: "Ada Quintana",
    role: "Seguimiento de Envíos",
    dept: "logistica",
    bio: "Sigue los 1.240 paquetes en tránsito y avisa al cliente antes de que pregunte. Cuando una agencia falla, abre la incidencia sola.",
    model: "haiku-4.5",
    tools: ["Correos", "SEUR", "Shopify", "Intercom"],
    tasks: [
      "Rastreando 1.240 envíos en tránsito",
      "Avisando de 22 entregas con retraso previsto",
      "Abriendo incidencia por 5 paquetes detenidos",
      "Actualizando el estado en la tienda online",
      "Midiendo el cumplimiento de plazo por agencia",
    ],
    palette: P(HAIR[5], SKIN[0], "#A88CFF", "#2E2C52", "#191732", "#DDD1FF"),
    deployedDays: 183,
    baseRuns: 104280,
    baseHours: 8.6,
    cadence: 3,
    successRate: 99.1,
    avgRuntime: 6,
    valuePerRun: 19,
    savedPerRun: 0.08,
    skills: [
      { label: "Cobertura", value: 99 },
      { label: "Aviso", value: 95 },
      { label: "Volumen", value: 98 },
    ],
  },
  {
    id: "log-05",
    name: "Néstor Gil",
    role: "Devoluciones y Postventa",
    dept: "logistica",
    bio: "Resuelve cada devolución decidiendo si repone, repara o reembolsa según el histórico del cliente. Detecta el patrón cuando un producto vuelve demasiado.",
    model: "sonnet-5",
    tools: ["Shopify", "Zendesk", "SAP", "Stripe"],
    tasks: [
      "Resolviendo 41 devoluciones pendientes",
      "Detectando defecto repetido en la referencia AR-220",
      "Autorizando 12 reembolsos dentro de política",
      "Reincorporando 28 unidades al stock vendible",
      "Midiendo el coste real de la logística inversa",
    ],
    palette: P(HAIR[4], SKIN[1], "#8E77E8", "#2A2748", "#15132A", "#C9BCFF"),
    deployedDays: 171,
    baseRuns: 38510,
    baseHours: 7.2,
    cadence: 8,
    successRate: 98.5,
    avgRuntime: 27,
    valuePerRun: 46,
    savedPerRun: 0.2,
    skills: [
      { label: "Resolución", value: 94 },
      { label: "Patrones", value: 88 },
      { label: "Coste", value: 86 },
    ],
  },
  {
    id: "log-06",
    name: "Pilar Aroca",
    role: "Previsión de Demanda",
    dept: "logistica",
    bio: "Proyecta la demanda de las próximas ocho semanas cruzando ventas, campañas y estacionalidad. Su previsión es la que dispara las compras del mes siguiente.",
    model: "opus-5",
    tools: ["Snowflake", "Prophet", "Looker", "SAP"],
    tasks: [
      "Proyectando demanda de 8 semanas por familia",
      "Incorporando el efecto de la campaña de vuelta al cole",
      "Corrigiendo la previsión tras el pico del fin de semana",
      "Comparando error de previsión del último mes",
      "Recomendando compra anticipada de 4 referencias",
    ],
    palette: P(HAIR[6], SKIN[3], "#B79CFF", "#302D56", "#1B1836", "#E4DBFF"),
    deployedDays: 149,
    baseRuns: 11840,
    baseHours: 5.6,
    cadence: 21,
    successRate: 96.9,
    avgRuntime: 83,
    valuePerRun: 192,
    savedPerRun: 0.44,
    skills: [
      { label: "Modelado", value: 96 },
      { label: "Estacionalidad", value: 92 },
      { label: "Precisión", value: 87 },
    ],
  },
];

/** Se deriva del roster para que los contadores de la interfaz nunca se desfasen. */
export const AGENT_COUNT = ROSTER.length;

/** El único agente que ejecuta trabajo real contra APIs externas, no simulado. */
export const LEAD_HUNTER_ID = "mkt-08";

/** El que planifica el reparto de verdad, con distancias reales de calle. */
export const ROUTE_PLANNER_ID = "log-01";

export const AGENTS_BY_DEPT = {
  marketing: ROSTER.filter((a) => a.dept === "marketing"),
  ventas: ROSTER.filter((a) => a.dept === "ventas"),
  contabilidad: ROSTER.filter((a) => a.dept === "contabilidad"),
  logistica: ROSTER.filter((a) => a.dept === "logistica"),
};
